### PR TITLE
Testing a few GHA configurations

### PR DESCRIPTION
**Pull request by jeroen**
To fix your GHA problems raised in: https://github.com/ropensci/magick/issues/235

### CODE REVIEW

**Comment by yonicd** [comment]
it seems all the RStudio based builds are failing. Is this an issue that should be opened somewhere else or to continue the thread in magick?

**Comment by jeroen** [comment]
I think I understand the issue, but it's a bit complicated. Let me try some other things first.

**Comment by yonicd** [comment]
Ok. Thanks. Btw the gha branch has a shorter build time since it is targeting magick instead of the full texPreview build.

In the commit msg you can add skip [osx|winos|linux] to skip os specific builds

**Comment by jeroen** [comment]
Hi @yonicd I have updated this PR. RSPM should now work icw/ ubuntu 18 and 20. It still doesn't work on Ubuntu 16, however that system is almost EOL so maybe that's not a big issue.

You can merge this if you like.

**Comment by yonicd** [comment]
Thank you for getting this to work. 

I know of quite a few people who had this problem. I will share the configuration with them.

Thanks!

**Pull request merged**
